// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pushover

import (
	"github.com/gregdel/pushover"
	mock "github.com/stretchr/testify/mock"
)

// newMockpushoverClient creates a new instance of mockpushoverClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockpushoverClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockpushoverClient {
	_ = "STUB: not implemented"
	return nil
}

// mockpushoverClient is an autogenerated mock type for the pushoverClient type
type mockpushoverClient struct {
	mock.Mock
}

type mockpushoverClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockpushoverClient) EXPECT() *mockpushoverClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// SendMessage provides a mock function for the type mockpushoverClient
func (_mock *mockpushoverClient) SendMessage(message *pushover.Message, recipient *pushover.Recipient) (*pushover.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// mockpushoverClient_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type mockpushoverClient_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - message *pushover.Message
//   - recipient *pushover.Recipient
func (_e *mockpushoverClient_Expecter) SendMessage(message interface{}, recipient interface{}) *mockpushoverClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockpushoverClient_SendMessage_Call) Run(run func(message *pushover.Message, recipient *pushover.Recipient)) *mockpushoverClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockpushoverClient_SendMessage_Call) Return(response *pushover.Response, err error) *mockpushoverClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockpushoverClient_SendMessage_Call) RunAndReturn(run func(message *pushover.Message, recipient *pushover.Recipient) (*pushover.Response, error)) *mockpushoverClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}
