// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package matrix

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"maunium.net/go/mautrix"
	"maunium.net/go/mautrix/event"
	"maunium.net/go/mautrix/id"
)

// newMockmatrixClient creates a new instance of mockmatrixClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmatrixClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmatrixClient {
	_ = "STUB: not implemented"
	return nil
}

// mockmatrixClient is an autogenerated mock type for the matrixClient type
type mockmatrixClient struct {
	mock.Mock
}

type mockmatrixClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmatrixClient) EXPECT() *mockmatrixClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// SendMessageEvent provides a mock function for the type mockmatrixClient
func (_mock *mockmatrixClient) SendMessageEvent(ctx context.Context, roomID id.RoomID, eventType event.Type, contentJSON any, extra ...mautrix.ReqSendEvent) (*mautrix.RespSendEvent, error) {
	_ = "STUB: not implemented"
	// mautrix.ReqSendEvent
	return nil, nil
}

// mockmatrixClient_SendMessageEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageEvent'
type mockmatrixClient_SendMessageEvent_Call struct {
	*mock.Call
}

// SendMessageEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID id.RoomID
//   - eventType event.Type
//   - contentJSON any
//   - extra ...mautrix.ReqSendEvent
func (_e *mockmatrixClient_Expecter) SendMessageEvent(ctx interface{}, roomID interface{}, eventType interface{}, contentJSON interface{}, extra ...interface{}) *mockmatrixClient_SendMessageEvent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockmatrixClient_SendMessageEvent_Call) Run(run func(ctx context.Context, roomID id.RoomID, eventType event.Type, contentJSON any, extra ...mautrix.ReqSendEvent)) *mockmatrixClient_SendMessageEvent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockmatrixClient_SendMessageEvent_Call) Return(resp *mautrix.RespSendEvent, err error) *mockmatrixClient_SendMessageEvent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockmatrixClient_SendMessageEvent_Call) RunAndReturn(run func(ctx context.Context, roomID id.RoomID, eventType event.Type, contentJSON any, extra ...mautrix.ReqSendEvent) (*mautrix.RespSendEvent, error)) *mockmatrixClient_SendMessageEvent_Call {
	_ = "STUB: not implemented"
	return nil
}
