// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package amazonses

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ses"
	mock "github.com/stretchr/testify/mock"
)

// newMocksesClient creates a new instance of mocksesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksesClient {
	_ = "STUB: not implemented"
	return nil
}

// mocksesClient is an autogenerated mock type for the sesClient type
type mocksesClient struct {
	mock.Mock
}

type mocksesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksesClient) EXPECT() *mocksesClient_Expecter { _ = "STUB: not implemented"; return nil }

// SendEmail provides a mock function for the type mocksesClient
func (_mock *mocksesClient) SendEmail(ctx context.Context, params *ses.SendEmailInput, optFns ...func(options *ses.Options)) (*ses.SendEmailOutput, error) {
	_ = "STUB: not implemented"
	// func(options *ses.Options)
	return nil, nil
}

// mocksesClient_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type mocksesClient_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - params *ses.SendEmailInput
//   - optFns ...func(options *ses.Options)
func (_e *mocksesClient_Expecter) SendEmail(ctx interface{}, params interface{}, optFns ...interface{}) *mocksesClient_SendEmail_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksesClient_SendEmail_Call) Run(run func(ctx context.Context, params *ses.SendEmailInput, optFns ...func(options *ses.Options))) *mocksesClient_SendEmail_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksesClient_SendEmail_Call) Return(sendEmailOutput *ses.SendEmailOutput, err error) *mocksesClient_SendEmail_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksesClient_SendEmail_Call) RunAndReturn(run func(ctx context.Context, params *ses.SendEmailInput, optFns ...func(options *ses.Options)) (*ses.SendEmailOutput, error)) *mocksesClient_SendEmail_Call {
	_ = "STUB: not implemented"
	return nil
}
