// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package viber

import (
	"github.com/mileusna/viber"
	mock "github.com/stretchr/testify/mock"
)

// newMockviberClient creates a new instance of mockviberClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockviberClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockviberClient {
	_ = "STUB: not implemented"
	return nil
}

// mockviberClient is an autogenerated mock type for the viberClient type
type mockviberClient struct {
	mock.Mock
}

type mockviberClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockviberClient) EXPECT() *mockviberClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// SendTextMessage provides a mock function for the type mockviberClient
func (_mock *mockviberClient) SendTextMessage(receiver string, msg string) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// mockviberClient_SendTextMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTextMessage'
type mockviberClient_SendTextMessage_Call struct {
	*mock.Call
}

// SendTextMessage is a helper method to define mock.On call
//   - receiver string
//   - msg string
func (_e *mockviberClient_Expecter) SendTextMessage(receiver interface{}, msg interface{}) *mockviberClient_SendTextMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockviberClient_SendTextMessage_Call) Run(run func(receiver string, msg string)) *mockviberClient_SendTextMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockviberClient_SendTextMessage_Call) Return(v uint64, err error) *mockviberClient_SendTextMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockviberClient_SendTextMessage_Call) RunAndReturn(run func(receiver string, msg string) (uint64, error)) *mockviberClient_SendTextMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

// SetWebhook provides a mock function for the type mockviberClient
func (_mock *mockviberClient) SetWebhook(url string, eventTypes []string) (viber.WebhookResp, error) {
	_ = "STUB: not implemented"
	return *new(viber.WebhookResp), nil
}

// mockviberClient_SetWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWebhook'
type mockviberClient_SetWebhook_Call struct {
	*mock.Call
}

// SetWebhook is a helper method to define mock.On call
//   - url string
//   - eventTypes []string
func (_e *mockviberClient_Expecter) SetWebhook(url interface{}, eventTypes interface{}) *mockviberClient_SetWebhook_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockviberClient_SetWebhook_Call) Run(run func(url string, eventTypes []string)) *mockviberClient_SetWebhook_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockviberClient_SetWebhook_Call) Return(webhookResp viber.WebhookResp, err error) *mockviberClient_SetWebhook_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockviberClient_SetWebhook_Call) RunAndReturn(run func(url string, eventTypes []string) (viber.WebhookResp, error)) *mockviberClient_SetWebhook_Call {
	_ = "STUB: not implemented"
	return nil
}
