// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lark

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksender creates a new instance of mocksender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksender {
	_ = "STUB: not implemented"
	return nil
}

// mocksender is an autogenerated mock type for the sender type
type mocksender struct {
	mock.Mock
}

type mocksender_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksender) EXPECT() *mocksender_Expecter { _ = "STUB: not implemented"; return nil }

// Send provides a mock function for the type mocksender
func (_mock *mocksender) Send(subject string, message string) error {
	_ = "STUB: not implemented"
	return nil
}

// mocksender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mocksender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - subject string
//   - message string
func (_e *mocksender_Expecter) Send(subject interface{}, message interface{}) *mocksender_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksender_Send_Call) Run(run func(subject string, message string)) *mocksender_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksender_Send_Call) Return(err error) *mocksender_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksender_Send_Call) RunAndReturn(run func(subject string, message string) error) *mocksender_Send_Call {
	_ = "STUB: not implemented"
	return nil
}
