// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lark

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksendToer creates a new instance of mocksendToer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksendToer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksendToer {
	_ = "STUB: not implemented"
	return nil
}

// mocksendToer is an autogenerated mock type for the sendToer type
type mocksendToer struct {
	mock.Mock
}

type mocksendToer_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksendToer) EXPECT() *mocksendToer_Expecter { _ = "STUB: not implemented"; return nil }

// SendTo provides a mock function for the type mocksendToer
func (_mock *mocksendToer) SendTo(subject string, message string, id string, idType string) error {
	_ = "STUB: not implemented"
	return nil
}

// mocksendToer_SendTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTo'
type mocksendToer_SendTo_Call struct {
	*mock.Call
}

// SendTo is a helper method to define mock.On call
//   - subject string
//   - message string
//   - id string
//   - idType string
func (_e *mocksendToer_Expecter) SendTo(subject interface{}, message interface{}, id interface{}, idType interface{}) *mocksendToer_SendTo_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksendToer_SendTo_Call) Run(run func(subject string, message string, id string, idType string)) *mocksendToer_SendTo_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksendToer_SendTo_Call) Return(err error) *mocksendToer_SendTo_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksendToer_SendTo_Call) RunAndReturn(run func(subject string, message string, id string, idType string) error) *mocksendToer_SendTo_Call {
	_ = "STUB: not implemented"
	return nil
}
