// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package slack

import (
	"context"

	"github.com/slack-go/slack"
	mock "github.com/stretchr/testify/mock"
)

// newMockslackClient creates a new instance of mockslackClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockslackClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockslackClient {
	_ = "STUB: not implemented"
	return nil
}

// mockslackClient is an autogenerated mock type for the slackClient type
type mockslackClient struct {
	mock.Mock
}

type mockslackClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockslackClient) EXPECT() *mockslackClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// PostMessageContext provides a mock function for the type mockslackClient
func (_mock *mockslackClient) PostMessageContext(ctx context.Context, channelID string, options ...slack.MsgOption) (string, string, error) {
	_ = "STUB: not implemented"
	// slack.MsgOption
	return "", "", nil
}

// mockslackClient_PostMessageContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostMessageContext'
type mockslackClient_PostMessageContext_Call struct {
	*mock.Call
}

// PostMessageContext is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID string
//   - options ...slack.MsgOption
func (_e *mockslackClient_Expecter) PostMessageContext(ctx interface{}, channelID interface{}, options ...interface{}) *mockslackClient_PostMessageContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockslackClient_PostMessageContext_Call) Run(run func(ctx context.Context, channelID string, options ...slack.MsgOption)) *mockslackClient_PostMessageContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockslackClient_PostMessageContext_Call) Return(s string, s1 string, err error) *mockslackClient_PostMessageContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockslackClient_PostMessageContext_Call) RunAndReturn(run func(ctx context.Context, channelID string, options ...slack.MsgOption) (string, string, error)) *mockslackClient_PostMessageContext_Call {
	_ = "STUB: not implemented"
	return nil
}
