// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package plivo

import (
	"github.com/plivo/plivo-go/v7"
	mock "github.com/stretchr/testify/mock"
)

// newMockplivoMsgClient creates a new instance of mockplivoMsgClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockplivoMsgClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockplivoMsgClient {
	_ = "STUB: not implemented"
	return nil
}

// mockplivoMsgClient is an autogenerated mock type for the plivoMsgClient type
type mockplivoMsgClient struct {
	mock.Mock
}

type mockplivoMsgClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockplivoMsgClient) EXPECT() *mockplivoMsgClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Create provides a mock function for the type mockplivoMsgClient
func (_mock *mockplivoMsgClient) Create(messageCreateParams plivo.MessageCreateParams) (*plivo.MessageCreateResponseBody, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// mockplivoMsgClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockplivoMsgClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - messageCreateParams plivo.MessageCreateParams
func (_e *mockplivoMsgClient_Expecter) Create(messageCreateParams interface{}) *mockplivoMsgClient_Create_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockplivoMsgClient_Create_Call) Run(run func(messageCreateParams plivo.MessageCreateParams)) *mockplivoMsgClient_Create_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockplivoMsgClient_Create_Call) Return(messageCreateResponseBody *plivo.MessageCreateResponseBody, err error) *mockplivoMsgClient_Create_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockplivoMsgClient_Create_Call) RunAndReturn(run func(messageCreateParams plivo.MessageCreateParams) (*plivo.MessageCreateResponseBody, error)) *mockplivoMsgClient_Create_Call {
	_ = "STUB: not implemented"
	return nil
}
