// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wechat

import (
	"github.com/silenceper/wechat/v2/officialaccount/message"
	mock "github.com/stretchr/testify/mock"
)

// newMockwechatMessageManager creates a new instance of mockwechatMessageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockwechatMessageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockwechatMessageManager {
	_ = "STUB: not implemented"
	return nil
}

// mockwechatMessageManager is an autogenerated mock type for the wechatMessageManager type
type mockwechatMessageManager struct {
	mock.Mock
}

type mockwechatMessageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockwechatMessageManager) EXPECT() *mockwechatMessageManager_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Send provides a mock function for the type mockwechatMessageManager
func (_mock *mockwechatMessageManager) Send(msg *message.CustomerMessage) error {
	_ = "STUB: not implemented"
	return nil
}

// mockwechatMessageManager_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockwechatMessageManager_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg *message.CustomerMessage
func (_e *mockwechatMessageManager_Expecter) Send(msg interface{}) *mockwechatMessageManager_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockwechatMessageManager_Send_Call) Run(run func(msg *message.CustomerMessage)) *mockwechatMessageManager_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockwechatMessageManager_Send_Call) Return(err error) *mockwechatMessageManager_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockwechatMessageManager_Send_Call) RunAndReturn(run func(msg *message.CustomerMessage) error) *mockwechatMessageManager_Send_Call {
	_ = "STUB: not implemented"
	return nil
}
