// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package msteams

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// newMockteamsClient creates a new instance of mockteamsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockteamsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockteamsClient {
	_ = "STUB: not implemented"
	return nil
}

// mockteamsClient is an autogenerated mock type for the teamsClient type
type mockteamsClient struct {
	mock.Mock
}

type mockteamsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockteamsClient) EXPECT() *mockteamsClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// SendWithContext provides a mock function for the type mockteamsClient
func (_mock *mockteamsClient) SendWithContext(ctx context.Context, webhookURL string, message goteamsnotify.TeamsMessage) error {
	_ = "STUB: not implemented"
	return nil
}

// mockteamsClient_SendWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWithContext'
type mockteamsClient_SendWithContext_Call struct {
	*mock.Call
}

// SendWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - webhookURL string
//   - message goteamsnotify.TeamsMessage
func (_e *mockteamsClient_Expecter) SendWithContext(ctx interface{}, webhookURL interface{}, message interface{}) *mockteamsClient_SendWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SendWithContext_Call) Run(run func(ctx context.Context, webhookURL string, message goteamsnotify.TeamsMessage)) *mockteamsClient_SendWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SendWithContext_Call) Return(err error) *mockteamsClient_SendWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SendWithContext_Call) RunAndReturn(run func(ctx context.Context, webhookURL string, message goteamsnotify.TeamsMessage) error) *mockteamsClient_SendWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient provides a mock function for the type mockteamsClient
func (_mock *mockteamsClient) SetHTTPClient(httpClient *http.Client) *goteamsnotify.TeamsClient {
	_ = "STUB: not implemented"
	return nil
}

// mockteamsClient_SetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHTTPClient'
type mockteamsClient_SetHTTPClient_Call struct {
	*mock.Call
}

// SetHTTPClient is a helper method to define mock.On call
//   - httpClient *http.Client
func (_e *mockteamsClient_Expecter) SetHTTPClient(httpClient interface{}) *mockteamsClient_SetHTTPClient_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SetHTTPClient_Call) Run(run func(httpClient *http.Client)) *mockteamsClient_SetHTTPClient_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SetHTTPClient_Call) Return(teamsClient *goteamsnotify.TeamsClient) *mockteamsClient_SetHTTPClient_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SetHTTPClient_Call) RunAndReturn(run func(httpClient *http.Client) *goteamsnotify.TeamsClient) *mockteamsClient_SetHTTPClient_Call {
	_ = "STUB: not implemented"
	return nil
}

// SetUserAgent provides a mock function for the type mockteamsClient
func (_mock *mockteamsClient) SetUserAgent(userAgent string) *goteamsnotify.TeamsClient {
	_ = "STUB: not implemented"
	return nil
}

// mockteamsClient_SetUserAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserAgent'
type mockteamsClient_SetUserAgent_Call struct {
	*mock.Call
}

// SetUserAgent is a helper method to define mock.On call
//   - userAgent string
func (_e *mockteamsClient_Expecter) SetUserAgent(userAgent interface{}) *mockteamsClient_SetUserAgent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SetUserAgent_Call) Run(run func(userAgent string)) *mockteamsClient_SetUserAgent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SetUserAgent_Call) Return(teamsClient *goteamsnotify.TeamsClient) *mockteamsClient_SetUserAgent_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SetUserAgent_Call) RunAndReturn(run func(userAgent string) *goteamsnotify.TeamsClient) *mockteamsClient_SetUserAgent_Call {
	_ = "STUB: not implemented"
	return nil
}

// SkipWebhookURLValidationOnSend provides a mock function for the type mockteamsClient
func (_mock *mockteamsClient) SkipWebhookURLValidationOnSend(skip bool) *goteamsnotify.TeamsClient {
	_ = "STUB: not implemented"
	return nil
}

// mockteamsClient_SkipWebhookURLValidationOnSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SkipWebhookURLValidationOnSend'
type mockteamsClient_SkipWebhookURLValidationOnSend_Call struct {
	*mock.Call
}

// SkipWebhookURLValidationOnSend is a helper method to define mock.On call
//   - skip bool
func (_e *mockteamsClient_Expecter) SkipWebhookURLValidationOnSend(skip interface{}) *mockteamsClient_SkipWebhookURLValidationOnSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SkipWebhookURLValidationOnSend_Call) Run(run func(skip bool)) *mockteamsClient_SkipWebhookURLValidationOnSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SkipWebhookURLValidationOnSend_Call) Return(teamsClient *goteamsnotify.TeamsClient) *mockteamsClient_SkipWebhookURLValidationOnSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockteamsClient_SkipWebhookURLValidationOnSend_Call) RunAndReturn(run func(skip bool) *goteamsnotify.TeamsClient) *mockteamsClient_SkipWebhookURLValidationOnSend_Call {
	_ = "STUB: not implemented"
	return nil
}
