// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package discord

import (
	"github.com/bwmarrin/discordgo"
	mock "github.com/stretchr/testify/mock"
)

// newMockdiscordSession creates a new instance of mockdiscordSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdiscordSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdiscordSession {
	_ = "STUB: not implemented"
	return nil
}

// mockdiscordSession is an autogenerated mock type for the discordSession type
type mockdiscordSession struct {
	mock.Mock
}

type mockdiscordSession_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdiscordSession) EXPECT() *mockdiscordSession_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// ChannelMessageSend provides a mock function for the type mockdiscordSession
func (_mock *mockdiscordSession) ChannelMessageSend(channelID string, content string, options ...discordgo.RequestOption) (*discordgo.Message, error) {
	_ = "STUB: not implemented"
	// discordgo.RequestOption
	return nil, nil
}

// mockdiscordSession_ChannelMessageSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChannelMessageSend'
type mockdiscordSession_ChannelMessageSend_Call struct {
	*mock.Call
}

// ChannelMessageSend is a helper method to define mock.On call
//   - channelID string
//   - content string
//   - options ...discordgo.RequestOption
func (_e *mockdiscordSession_Expecter) ChannelMessageSend(channelID interface{}, content interface{}, options ...interface{}) *mockdiscordSession_ChannelMessageSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockdiscordSession_ChannelMessageSend_Call) Run(run func(channelID string, content string, options ...discordgo.RequestOption)) *mockdiscordSession_ChannelMessageSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockdiscordSession_ChannelMessageSend_Call) Return(message *discordgo.Message, err error) *mockdiscordSession_ChannelMessageSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockdiscordSession_ChannelMessageSend_Call) RunAndReturn(run func(channelID string, content string, options ...discordgo.RequestOption) (*discordgo.Message, error)) *mockdiscordSession_ChannelMessageSend_Call {
	_ = "STUB: not implemented"
	return nil
}
