// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package googlechat

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/api/chat/v1"
)

// newMockspacesMessageCreator creates a new instance of mockspacesMessageCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockspacesMessageCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockspacesMessageCreator {
	_ = "STUB: not implemented"
	return nil
}

// mockspacesMessageCreator is an autogenerated mock type for the spacesMessageCreator type
type mockspacesMessageCreator struct {
	mock.Mock
}

type mockspacesMessageCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockspacesMessageCreator) EXPECT() *mockspacesMessageCreator_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Create provides a mock function for the type mockspacesMessageCreator
func (_mock *mockspacesMessageCreator) Create(s string, message *chat.Message) callCreator {
	_ = "STUB: not implemented"
	return *new(callCreator)
}

// mockspacesMessageCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockspacesMessageCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - s string
//   - message *chat.Message
func (_e *mockspacesMessageCreator_Expecter) Create(s interface{}, message interface{}) *mockspacesMessageCreator_Create_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockspacesMessageCreator_Create_Call) Run(run func(s string, message *chat.Message)) *mockspacesMessageCreator_Create_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockspacesMessageCreator_Create_Call) Return(callCreatorMoqParam callCreator) *mockspacesMessageCreator_Create_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockspacesMessageCreator_Create_Call) RunAndReturn(run func(s string, message *chat.Message) callCreator) *mockspacesMessageCreator_Create_Call {
	_ = "STUB: not implemented"
	return nil
}
