// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package googlechat

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/api/chat/v1"
	"google.golang.org/api/googleapi"
)

// newMockcallCreator creates a new instance of mockcallCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockcallCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockcallCreator {
	_ = "STUB: not implemented"
	return nil
}

// mockcallCreator is an autogenerated mock type for the callCreator type
type mockcallCreator struct {
	mock.Mock
}

type mockcallCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockcallCreator) EXPECT() *mockcallCreator_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Do provides a mock function for the type mockcallCreator
func (_mock *mockcallCreator) Do(callOptions ...googleapi.CallOption) (*chat.Message, error) {
	_ = "STUB: not implemented"
	// googleapi.CallOption
	return nil, nil
}

// mockcallCreator_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type mockcallCreator_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - callOptions ...googleapi.CallOption
func (_e *mockcallCreator_Expecter) Do(callOptions ...interface{}) *mockcallCreator_Do_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockcallCreator_Do_Call) Run(run func(callOptions ...googleapi.CallOption)) *mockcallCreator_Do_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockcallCreator_Do_Call) Return(message *chat.Message, err error) *mockcallCreator_Do_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockcallCreator_Do_Call) RunAndReturn(run func(callOptions ...googleapi.CallOption) (*chat.Message, error)) *mockcallCreator_Do_Call {
	_ = "STUB: not implemented"
	return nil
}
