// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reddit

import (
	"context"

	"github.com/caarlos0/go-reddit/v3/reddit"
	mock "github.com/stretchr/testify/mock"
)

// newMockredditMessageClient creates a new instance of mockredditMessageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockredditMessageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockredditMessageClient {
	_ = "STUB: not implemented"
	return nil
}

// mockredditMessageClient is an autogenerated mock type for the redditMessageClient type
type mockredditMessageClient struct {
	mock.Mock
}

type mockredditMessageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockredditMessageClient) EXPECT() *mockredditMessageClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Send provides a mock function for the type mockredditMessageClient
func (_mock *mockredditMessageClient) Send(context1 context.Context, sendMessageRequest *reddit.SendMessageRequest) (*reddit.Response, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// mockredditMessageClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockredditMessageClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - context1 context.Context
//   - sendMessageRequest *reddit.SendMessageRequest
func (_e *mockredditMessageClient_Expecter) Send(context1 interface{}, sendMessageRequest interface{}) *mockredditMessageClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockredditMessageClient_Send_Call) Run(run func(context1 context.Context, sendMessageRequest *reddit.SendMessageRequest)) *mockredditMessageClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockredditMessageClient_Send_Call) Return(response *reddit.Response, err error) *mockredditMessageClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockredditMessageClient_Send_Call) RunAndReturn(run func(context1 context.Context, sendMessageRequest *reddit.SendMessageRequest) (*reddit.Response, error)) *mockredditMessageClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}
