// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pagerduty

import (
	"context"

	"github.com/PagerDuty/go-pagerduty"
	mock "github.com/stretchr/testify/mock"
)

// newMockClient creates a new instance of mockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockClient {
	_ = "STUB: not implemented"
	return nil
}

// mockClient is an autogenerated mock type for the Client type
type mockClient struct {
	mock.Mock
}

type mockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockClient) EXPECT() *mockClient_Expecter { _ = "STUB: not implemented"; return nil }

// CreateIncidentWithContext provides a mock function for the type mockClient
func (_mock *mockClient) CreateIncidentWithContext(ctx context.Context, from string, options *pagerduty.CreateIncidentOptions) (*pagerduty.Incident, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// mockClient_CreateIncidentWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIncidentWithContext'
type mockClient_CreateIncidentWithContext_Call struct {
	*mock.Call
}

// CreateIncidentWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - options *pagerduty.CreateIncidentOptions
func (_e *mockClient_Expecter) CreateIncidentWithContext(ctx interface{}, from interface{}, options interface{}) *mockClient_CreateIncidentWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockClient_CreateIncidentWithContext_Call) Run(run func(ctx context.Context, from string, options *pagerduty.CreateIncidentOptions)) *mockClient_CreateIncidentWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockClient_CreateIncidentWithContext_Call) Return(incident *pagerduty.Incident, err error) *mockClient_CreateIncidentWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockClient_CreateIncidentWithContext_Call) RunAndReturn(run func(ctx context.Context, from string, options *pagerduty.CreateIncidentOptions) (*pagerduty.Incident, error)) *mockClient_CreateIncidentWithContext_Call {
	_ = "STUB: not implemented"
	return nil
}
