// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package twilio

import (
	"net/url"

	"github.com/kevinburke/twilio-go"
	mock "github.com/stretchr/testify/mock"
)

// newMocktwilioClient creates a new instance of mocktwilioClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktwilioClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktwilioClient {
	_ = "STUB: not implemented"
	return nil
}

// mocktwilioClient is an autogenerated mock type for the twilioClient type
type mocktwilioClient struct {
	mock.Mock
}

type mocktwilioClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktwilioClient) EXPECT() *mocktwilioClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// SendMessage provides a mock function for the type mocktwilioClient
func (_mock *mocktwilioClient) SendMessage(from string, to string, body string, mediaURLs []*url.URL) (*twilio.Message, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// mocktwilioClient_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type mocktwilioClient_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - from string
//   - to string
//   - body string
//   - mediaURLs []*url.URL
func (_e *mocktwilioClient_Expecter) SendMessage(from interface{}, to interface{}, body interface{}, mediaURLs interface{}) *mocktwilioClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocktwilioClient_SendMessage_Call) Run(run func(from string, to string, body string, mediaURLs []*url.URL)) *mocktwilioClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocktwilioClient_SendMessage_Call) Return(message *twilio.Message, err error) *mocktwilioClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocktwilioClient_SendMessage_Call) RunAndReturn(run func(from string, to string, body string, mediaURLs []*url.URL) (*twilio.Message, error)) *mocktwilioClient_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}
