// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mattermost

import (
	"context"

	"github.com/nikoksr/notify/service/http"
	mock "github.com/stretchr/testify/mock"
)

// newMockhttpClient creates a new instance of mockhttpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhttpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhttpClient {
	_ = "STUB: not implemented"
	return nil
}

// mockhttpClient is an autogenerated mock type for the httpClient type
type mockhttpClient struct {
	mock.Mock
}

type mockhttpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhttpClient) EXPECT() *mockhttpClient_Expecter { _ = "STUB: not implemented"; return nil }

// AddReceivers provides a mock function for the type mockhttpClient
func (_mock *mockhttpClient) AddReceivers(wh ...*http.Webhook) {
	_ = "STUB: not implemented"
	// *http.Webhook
	return
}

// mockhttpClient_AddReceivers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReceivers'
type mockhttpClient_AddReceivers_Call struct {
	*mock.Call
}

// AddReceivers is a helper method to define mock.On call
//   - wh ...*http.Webhook
func (_e *mockhttpClient_Expecter) AddReceivers(wh ...interface{}) *mockhttpClient_AddReceivers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_AddReceivers_Call) Run(run func(wh ...*http.Webhook)) *mockhttpClient_AddReceivers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_AddReceivers_Call) Return() *mockhttpClient_AddReceivers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_AddReceivers_Call) RunAndReturn(run func(wh ...*http.Webhook)) *mockhttpClient_AddReceivers_Call {
	_ = "STUB: not implemented"
	return nil

	// PostSend provides a mock function for the type mockhttpClient
}

func (_mock *mockhttpClient) PostSend(postfn http.PostSendHookFn) {
	_ = "STUB: not implemented"
	return
}

// mockhttpClient_PostSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostSend'
type mockhttpClient_PostSend_Call struct {
	*mock.Call
}

// PostSend is a helper method to define mock.On call
//   - postfn http.PostSendHookFn
func (_e *mockhttpClient_Expecter) PostSend(postfn interface{}) *mockhttpClient_PostSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_PostSend_Call) Run(run func(postfn http.PostSendHookFn)) *mockhttpClient_PostSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_PostSend_Call) Return() *mockhttpClient_PostSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_PostSend_Call) RunAndReturn(run func(postfn http.PostSendHookFn)) *mockhttpClient_PostSend_Call {
	_ = "STUB: not implemented"
	return nil

	// PreSend provides a mock function for the type mockhttpClient
}

func (_mock *mockhttpClient) PreSend(prefn http.PreSendHookFn) { _ = "STUB: not implemented"; return }

// mockhttpClient_PreSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreSend'
type mockhttpClient_PreSend_Call struct {
	*mock.Call
}

// PreSend is a helper method to define mock.On call
//   - prefn http.PreSendHookFn
func (_e *mockhttpClient_Expecter) PreSend(prefn interface{}) *mockhttpClient_PreSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_PreSend_Call) Run(run func(prefn http.PreSendHookFn)) *mockhttpClient_PreSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_PreSend_Call) Return() *mockhttpClient_PreSend_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_PreSend_Call) RunAndReturn(run func(prefn http.PreSendHookFn)) *mockhttpClient_PreSend_Call {
	_ = "STUB: not implemented"
	return nil

	// Send provides a mock function for the type mockhttpClient
}

func (_mock *mockhttpClient) Send(ctx context.Context, subject string, message string) error {
	_ = "STUB: not implemented"
	return nil
}

// mockhttpClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockhttpClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - message string
func (_e *mockhttpClient_Expecter) Send(ctx interface{}, subject interface{}, message interface{}) *mockhttpClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_Send_Call) Run(run func(ctx context.Context, subject string, message string)) *mockhttpClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_Send_Call) Return(err error) *mockhttpClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockhttpClient_Send_Call) RunAndReturn(run func(ctx context.Context, subject string, message string) error) *mockhttpClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}
