// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package syslog

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksyslogWriter creates a new instance of mocksyslogWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksyslogWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksyslogWriter {
	_ = "STUB: not implemented"
	return nil
}

// mocksyslogWriter is an autogenerated mock type for the syslogWriter type
type mocksyslogWriter struct {
	mock.Mock
}

type mocksyslogWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksyslogWriter) EXPECT() *mocksyslogWriter_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// Close provides a mock function for the type mocksyslogWriter
func (_mock *mocksyslogWriter) Close() error { _ = "STUB: not implemented"; return nil }

// mocksyslogWriter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mocksyslogWriter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mocksyslogWriter_Expecter) Close() *mocksyslogWriter_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksyslogWriter_Close_Call) Run(run func()) *mocksyslogWriter_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksyslogWriter_Close_Call) Return(err error) *mocksyslogWriter_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksyslogWriter_Close_Call) RunAndReturn(run func() error) *mocksyslogWriter_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

// Write provides a mock function for the type mocksyslogWriter
func (_mock *mocksyslogWriter) Write(p []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// mocksyslogWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type mocksyslogWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *mocksyslogWriter_Expecter) Write(p interface{}) *mocksyslogWriter_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksyslogWriter_Write_Call) Run(run func(p []byte)) *mocksyslogWriter_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksyslogWriter_Write_Call) Return(n int, err error) *mocksyslogWriter_Write_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksyslogWriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *mocksyslogWriter_Write_Call {
	_ = "STUB: not implemented"
	return nil
}
