// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fcm

import (
	"context"

	"firebase.google.com/go/v4/messaging"
	mock "github.com/stretchr/testify/mock"
)

// newMockfcmClient creates a new instance of mockfcmClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockfcmClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockfcmClient {
	_ = "STUB: not implemented"
	return nil
}

// mockfcmClient is an autogenerated mock type for the fcmClient type
type mockfcmClient struct {
	mock.Mock
}

type mockfcmClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockfcmClient) EXPECT() *mockfcmClient_Expecter { _ = "STUB: not implemented"; return nil }

// Send provides a mock function for the type mockfcmClient
func (_mock *mockfcmClient) Send(ctx context.Context, message ...*messaging.Message) (*messaging.BatchResponse, error) {
	_ = "STUB: not implemented"
	// *messaging.Message
	return nil, nil
}

// mockfcmClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockfcmClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - message ...*messaging.Message
func (_e *mockfcmClient_Expecter) Send(ctx interface{}, message ...interface{}) *mockfcmClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockfcmClient_Send_Call) Run(run func(ctx context.Context, message ...*messaging.Message)) *mockfcmClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockfcmClient_Send_Call) Return(batchResponse *messaging.BatchResponse, err error) *mockfcmClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockfcmClient_Send_Call) RunAndReturn(run func(ctx context.Context, message ...*messaging.Message) (*messaging.BatchResponse, error)) *mockfcmClient_Send_Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMulticast provides a mock function for the type mockfcmClient
func (_mock *mockfcmClient) SendMulticast(ctx context.Context, message *messaging.MulticastMessage) (*messaging.BatchResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// mockfcmClient_SendMulticast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMulticast'
type mockfcmClient_SendMulticast_Call struct {
	*mock.Call
}

// SendMulticast is a helper method to define mock.On call
//   - ctx context.Context
//   - message *messaging.MulticastMessage
func (_e *mockfcmClient_Expecter) SendMulticast(ctx interface{}, message interface{}) *mockfcmClient_SendMulticast_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockfcmClient_SendMulticast_Call) Run(run func(ctx context.Context, message *messaging.MulticastMessage)) *mockfcmClient_SendMulticast_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockfcmClient_SendMulticast_Call) Return(batchResponse *messaging.BatchResponse, err error) *mockfcmClient_SendMulticast_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockfcmClient_SendMulticast_Call) RunAndReturn(run func(ctx context.Context, message *messaging.MulticastMessage) (*messaging.BatchResponse, error)) *mockfcmClient_SendMulticast_Call {
	_ = "STUB: not implemented"
	return nil
}
