// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package amazonsns

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sns"
	mock "github.com/stretchr/testify/mock"
)

// newMocksnsSendMessageAPI creates a new instance of mocksnsSendMessageAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksnsSendMessageAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksnsSendMessageAPI {
	_ = "STUB: not implemented"
	return nil
}

// mocksnsSendMessageAPI is an autogenerated mock type for the snsSendMessageAPI type
type mocksnsSendMessageAPI struct {
	mock.Mock
}

type mocksnsSendMessageAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksnsSendMessageAPI) EXPECT() *mocksnsSendMessageAPI_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// SendMessage provides a mock function for the type mocksnsSendMessageAPI
func (_mock *mocksnsSendMessageAPI) SendMessage(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error) {
	_ = "STUB: not implemented"
	// func(*sns.Options)
	return nil, nil
}

// mocksnsSendMessageAPI_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type mocksnsSendMessageAPI_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sns.PublishInput
//   - optFns ...func(*sns.Options)
func (_e *mocksnsSendMessageAPI_Expecter) SendMessage(ctx interface{}, params interface{}, optFns ...interface{}) *mocksnsSendMessageAPI_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksnsSendMessageAPI_SendMessage_Call) Run(run func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options))) *mocksnsSendMessageAPI_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksnsSendMessageAPI_SendMessage_Call) Return(publishOutput *sns.PublishOutput, err error) *mocksnsSendMessageAPI_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mocksnsSendMessageAPI_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)) *mocksnsSendMessageAPI_SendMessage_Call {
	_ = "STUB: not implemented"
	return nil
}
