// Code generated by mockery v2.43.2. DO NOT EDIT.

package mailgun

import mock "github.com/stretchr/testify/mock"

// mockOption is an autogenerated mock type for the Option type
type mockOption struct {
	mock.Mock
}

type mockOption_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOption) EXPECT() *mockOption_Expecter { _ = "STUB: not implemented"; return nil }

// Execute provides a mock function with given fields: _a0
func (_m *mockOption) Execute(_a0 *Mailgun) {
	_ = "STUB: not implemented"

	// mockOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
	return
}

type mockOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Mailgun
func (_e *mockOption_Expecter) Execute(_a0 interface{}) *mockOption_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockOption_Execute_Call) Run(run func(_a0 *Mailgun)) *mockOption_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockOption_Execute_Call) Return() *mockOption_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *mockOption_Execute_Call) RunAndReturn(run func(*Mailgun)) *mockOption_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

// newMockOption creates a new instance of mockOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOption {
	_ = "STUB: not implemented"
	return nil
}
